### Test /api/users route
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "user": {
    "username": "example",
    "email": "example@example.com",
    "password": "example"
  }
}

### Test /api/users/login route
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "example@example.com",
    "password": "example"
  }
}

### Test /api/user route
GET http://localhost:8000/api/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNjkyNDUyMTM2fQ.Q65RUliKq-0mlrNEkpypeJHc8tZsqi87SHTA0lHT5Fs


### Test /api/article route
POST http://localhost:8000/api/articles
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNjkyNDUyMTM2fQ.Q65RUliKq-0mlrNEkpypeJHc8tZsqi87SHTA0lHT5Fs