### Test /api/users route
POST http://localhost:8000/api/users
Content-Type: application/json

{
  "user": {
    "username": "example",
    "email": "example@example.com",
    "password": "example"
  }
}

### Test /api/users/login route
POST http://localhost:8000/api/users/login
Content-Type: application/json

{
  "user": {
    "email": "example@example.com",
    "password": "example"
  }
}

### Test /api/user route
GET http://localhost:8000/api/user
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNjkyNDUyMTM2fQ.Q65RUliKq-0mlrNEkpypeJHc8tZsqi87SHTA0lHT5Fs


### Test /api/articles route
POST http://localhost:8000/api/articles
Content-Type: application/json
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNjkyNDUyMTM2fQ.Q65RUliKq-0mlrNEkpypeJHc8tZsqi87SHTA0lHT5Fs

{
  "article": {
    "title": "example",
    "description": "example",
    "body": "example",
    "tagList": ["react"]
  }
}

### Test /api/articles/:slug route
GET http://localhost:8000/api/articles/example-ujbyui

### Test /api/articles get request
GET http://localhost:8000/api/articles?author=example&limit=2&offset=10

### Test /api/articles/:slug/favorites route
POST http://localhost:8000/api/articles/example-xi7oyl/favorite
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNjkyNDUyMTM2fQ.Q65RUliKq-0mlrNEkpypeJHc8tZsqi87SHTA0lHT5Fs

### Test /api/articles/:slug/favorites route
DELETE http://localhost:8000/api/articles/example-xi7oyl/favorite
Authorization: Token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwidXNlcm5hbWUiOiJleGFtcGxlIiwiZW1haWwiOiJleGFtcGxlQGV4YW1wbGUuY29tIiwiaWF0IjoxNjkyNDUyMTM2fQ.Q65RUliKq-0mlrNEkpypeJHc8tZsqi87SHTA0lHT5Fs

### Test /api/articles get request
GET http://localhost:8000/api/articles?favorited=example